
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.HBox hbox9;
	
	private global::Gtk.VBox labels_vbox;
	
	private global::Gtk.Label project_label;
	
	private global::Gtk.Label plarform_label;
	
	private global::Gtk.Label build_label;
	
	private global::Gtk.Label host_label;
	
	private global::Gtk.VBox vbox7;
	
	private global::Gtk.HBox hbox10;
	
	private global::Gtk.Entry project_entry;
	
	private global::Gtk.Button project_button;
	
	private global::Gtk.ComboBox platform_combobox;
	
	private global::Gtk.ComboBox build_combobox;
	
	private global::Gtk.HBox hbox11;
	
	private global::Gtk.Entry host_entry;
	
	private global::Gtk.Button button6;
	
	private global::Gtk.Button run_button;
	
	private global::Gtk.Statusbar statusbar1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Starter");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.labels_vbox = new global::Gtk.VBox ();
		this.labels_vbox.Name = "labels_vbox";
		this.labels_vbox.Homogeneous = true;
		this.labels_vbox.Spacing = 6;
		// Container child labels_vbox.Gtk.Box+BoxChild
		this.project_label = new global::Gtk.Label ();
		this.project_label.Name = "project_label";
		this.project_label.Xalign = 0F;
		this.project_label.LabelProp = global::Mono.Unix.Catalog.GetString ("Project:");
		this.labels_vbox.Add (this.project_label);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.labels_vbox [this.project_label]));
		w1.Position = 0;
		w1.Fill = false;
		// Container child labels_vbox.Gtk.Box+BoxChild
		this.plarform_label = new global::Gtk.Label ();
		this.plarform_label.Name = "plarform_label";
		this.plarform_label.Xalign = 0F;
		this.plarform_label.LabelProp = global::Mono.Unix.Catalog.GetString ("Platform:");
		this.labels_vbox.Add (this.plarform_label);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.labels_vbox [this.plarform_label]));
		w2.Position = 1;
		w2.Fill = false;
		// Container child labels_vbox.Gtk.Box+BoxChild
		this.build_label = new global::Gtk.Label ();
		this.build_label.Name = "build_label";
		this.build_label.Xalign = 0F;
		this.build_label.LabelProp = global::Mono.Unix.Catalog.GetString ("Build:");
		this.labels_vbox.Add (this.build_label);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.labels_vbox [this.build_label]));
		w3.Position = 2;
		w3.Fill = false;
		// Container child labels_vbox.Gtk.Box+BoxChild
		this.host_label = new global::Gtk.Label ();
		this.host_label.Name = "host_label";
		this.host_label.Xalign = 0F;
		this.host_label.LabelProp = global::Mono.Unix.Catalog.GetString ("Host:");
		this.labels_vbox.Add (this.host_label);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.labels_vbox [this.host_label]));
		w4.Position = 3;
		w4.Fill = false;
		this.hbox9.Add (this.labels_vbox);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.labels_vbox]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		w5.Padding = ((uint)(10));
		// Container child hbox9.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox ();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.project_entry = new global::Gtk.Entry ();
		this.project_entry.CanFocus = true;
		this.project_entry.Name = "project_entry";
		this.project_entry.IsEditable = true;
		this.project_entry.InvisibleChar = '●';
		this.hbox10.Add (this.project_entry);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.project_entry]));
		w6.Position = 0;
		// Container child hbox10.Gtk.Box+BoxChild
		this.project_button = new global::Gtk.Button ();
		this.project_button.CanFocus = true;
		this.project_button.Name = "project_button";
		this.project_button.UseUnderline = true;
		this.project_button.Label = global::Mono.Unix.Catalog.GetString ("...");
		this.hbox10.Add (this.project_button);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.project_button]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox7.Add (this.hbox10);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox10]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.platform_combobox = global::Gtk.ComboBox.NewText ();
		this.platform_combobox.AppendText (global::Mono.Unix.Catalog.GetString ("Linux32"));
		this.platform_combobox.AppendText (global::Mono.Unix.Catalog.GetString ("Linux64"));
		this.platform_combobox.AppendText (global::Mono.Unix.Catalog.GetString ("Windows32"));
		this.platform_combobox.AppendText (global::Mono.Unix.Catalog.GetString ("Windows64"));
		this.platform_combobox.AppendText (global::Mono.Unix.Catalog.GetString ("Android"));
		this.platform_combobox.Name = "platform_combobox";
		this.platform_combobox.Active = 0;
		this.vbox7.Add (this.platform_combobox);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.platform_combobox]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.build_combobox = global::Gtk.ComboBox.NewText ();
		this.build_combobox.AppendText (global::Mono.Unix.Catalog.GetString ("Debug"));
		this.build_combobox.AppendText (global::Mono.Unix.Catalog.GetString ("Development"));
		this.build_combobox.AppendText (global::Mono.Unix.Catalog.GetString ("Release"));
		this.build_combobox.Name = "build_combobox";
		this.build_combobox.Active = 0;
		this.vbox7.Add (this.build_combobox);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.build_combobox]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox ();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.host_entry = new global::Gtk.Entry ();
		this.host_entry.CanFocus = true;
		this.host_entry.Name = "host_entry";
		this.host_entry.Text = global::Mono.Unix.Catalog.GetString ("localhost");
		this.host_entry.IsEditable = true;
		this.host_entry.InvisibleChar = '●';
		this.hbox11.Add (this.host_entry);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.host_entry]));
		w11.Position = 0;
		// Container child hbox11.Gtk.Box+BoxChild
		this.button6 = new global::Gtk.Button ();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString ("...");
		this.hbox11.Add (this.button6);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.button6]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		this.vbox7.Add (this.hbox11);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox11]));
		w13.Position = 3;
		w13.Expand = false;
		w13.Fill = false;
		this.hbox9.Add (this.vbox7);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.vbox7]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		w14.Padding = ((uint)(10));
		this.vbox4.Add (this.hbox9);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox9]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.run_button = new global::Gtk.Button ();
		this.run_button.CanFocus = true;
		this.run_button.Name = "run_button";
		this.run_button.UseUnderline = true;
		this.run_button.BorderWidth = ((uint)(27));
		this.run_button.Label = global::Mono.Unix.Catalog.GetString ("Run");
		this.vbox4.Add (this.run_button);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.run_button]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		this.vbox4.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.statusbar1]));
		w17.Position = 2;
		w17.Expand = false;
		w17.Fill = false;
		this.Add (this.vbox4);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 291;
		this.DefaultHeight = 236;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.project_button.Clicked += new global::System.EventHandler (this.OnProjectButtonClicked);
		this.run_button.Clicked += new global::System.EventHandler (this.OnRunButtonClicked);
	}
}
