
// This file has been generated by the GUI designer. Do not modify.
namespace starter
{
	public partial class ProjectDialog
	{
		private global::Gtk.HBox hbox4;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label name_label;
		private global::Gtk.Label source_label;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Entry name_entry;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Entry source_entry;
		private global::Gtk.Button source_button;
		private global::Gtk.Button cancel_button;
		private global::Gtk.Button ok_button;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget starter.ProjectDialog
			this.Name = "starter.ProjectDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Projects");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(6));
			// Internal child starter.ProjectDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(10));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 4;
			// Container child vbox3.Gtk.Box+BoxChild
			this.name_label = new global::Gtk.Label ();
			this.name_label.Name = "name_label";
			this.name_label.Xalign = 0F;
			this.name_label.LabelProp = global::Mono.Unix.Catalog.GetString ("Name:");
			this.vbox3.Add (this.name_label);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.name_label]));
			w2.Position = 0;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.source_label = new global::Gtk.Label ();
			this.source_label.Name = "source_label";
			this.source_label.Xalign = 0F;
			this.source_label.LabelProp = global::Mono.Unix.Catalog.GetString ("Source:");
			this.vbox3.Add (this.source_label);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.source_label]));
			w3.Position = 1;
			w3.Fill = false;
			this.hbox4.Add (this.vbox3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox3]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.name_entry = new global::Gtk.Entry ();
			this.name_entry.CanFocus = true;
			this.name_entry.Name = "name_entry";
			this.name_entry.IsEditable = true;
			this.name_entry.InvisibleChar = '●';
			this.vbox4.Add (this.name_entry);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.name_entry]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.source_entry = new global::Gtk.Entry ();
			this.source_entry.CanFocus = true;
			this.source_entry.Name = "source_entry";
			this.source_entry.IsEditable = true;
			this.source_entry.InvisibleChar = '●';
			this.hbox5.Add (this.source_entry);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.source_entry]));
			w6.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.source_button = new global::Gtk.Button ();
			this.source_button.CanFocus = true;
			this.source_button.Name = "source_button";
			this.source_button.UseUnderline = true;
			this.source_button.Label = global::Mono.Unix.Catalog.GetString ("...");
			this.hbox5.Add (this.source_button);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.source_button]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox4.Add (this.hbox5);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox5]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.hbox4.Add (this.vbox4);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox4]));
			w9.Position = 1;
			w1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox4]));
			w10.Position = 0;
			w10.Fill = false;
			// Internal child starter.ProjectDialog.ActionArea
			global::Gtk.HButtonBox w11 = this.ActionArea;
			w11.Name = "dialog1_ActionArea";
			w11.Spacing = 10;
			w11.BorderWidth = ((uint)(5));
			w11.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.cancel_button = new global::Gtk.Button ();
			this.cancel_button.CanDefault = true;
			this.cancel_button.CanFocus = true;
			this.cancel_button.Name = "cancel_button";
			this.cancel_button.UseStock = true;
			this.cancel_button.UseUnderline = true;
			this.cancel_button.Label = "gtk-cancel";
			this.AddActionWidget (this.cancel_button, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w11 [this.cancel_button]));
			w12.Expand = false;
			w12.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.ok_button = new global::Gtk.Button ();
			this.ok_button.CanDefault = true;
			this.ok_button.CanFocus = true;
			this.ok_button.Name = "ok_button";
			this.ok_button.UseStock = true;
			this.ok_button.UseUnderline = true;
			this.ok_button.Label = "gtk-ok";
			this.AddActionWidget (this.ok_button, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w11 [this.ok_button]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 318;
			this.DefaultHeight = 166;
			this.Show ();
			this.source_button.Clicked += new global::System.EventHandler (this.OnSourceButtonClicked);
			this.ok_button.Clicked += new global::System.EventHandler (this.OnProjectDialogOkClicked);
		}
	}
}
