#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2012-2026 Daniele Bartolini et al.

set -eu

if [ $# -ne 3 ]; then
	echo "Usage: $0 <input> <symbol> <output.c>" >&2
	exit 1
fi

INPUT=$1
SYMBOL=$2
OUTPUT=$3

if [ ! -r "$INPUT" ]; then
	echo "Input file not found: ${INPUT}" >&2
	exit 1
fi

{
	printf "/* Generated by %s from %s. */\n\n" "${0##*/}" "${INPUT##*/}"
	printf "#include <stddef.h>\n\n"
	printf "static const unsigned char %s_data[] =\n{\n" "$SYMBOL"
	od -An -v -tx1 "$INPUT" | sed "s/[[:xdigit:]][[:xdigit:]]/0x&,/g; s/^ */\t/"
	printf "};\n\n"
	printf "const unsigned char *%s = %s_data;\n" "$SYMBOL" "$SYMBOL"
	printf "const size_t %s_size = sizeof(%s_data);\n" "$SYMBOL" "$SYMBOL"
} > "$OUTPUT"
