
// This file has been generated by the GUI designer. Do not modify.
namespace UnitEditor
{
	public partial class MainMenu
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget UnitEditor.MainMenu
			global::Stetic.BinContainer.Attach (this);
			this.Name = "UnitEditor.MainMenu";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
